spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pc?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 15070181343
    driver-class-name: com.mysql.cj.jdbc.Driver
resources-url:
  base-url: http://localhost:8888/static/
  image-out-url: src/main/resources/static/note-img/